HerkeseIs/HerkeseIs/Areas/Admin/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HerkeseIs.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using HerkeseIs.Areas.Admin.Models;

namespace HerkeseIs.Areas.Admin.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/Role
        public ActionResult Index()
        {
            var RoleStore = new RoleStore<IdentityRole>(context);
            var RoleManager = new RoleManager<IdentityRole>(RoleStore);
            var model = RoleManager.Roles.ToList();


            return View(model);
        }

        public ActionResult RoleEkle()
        {


            return View();
        }
        [HttpPost]
        public ActionResult RoleEkle(RoleEkleModelcs rol)
        {

            var RoleStore = new RoleStore<IdentityRole>(context);
            var RoleManager = new RoleManager<IdentityRole>(RoleStore);
           if( RoleManager.RoleExists(rol.RolAd) == false)
            {
                RoleManager.Create(new IdentityRole(rol.RolAd));
            }
            return RedirectToAction("Index");
        }

        public ActionResult RoleUserEkle()
        {
            return View();
        }
    }
}

HerkeseIs/HerkeseIs/Areas/Admin/Views/Role/Index.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


    
<div id="content" class="span10">

    <div class="container-fluid-full">
        <div class="row-fluid sortable">
            <div class="box span12">
                <div class="box-header" data-original-title>

                </div>
                <div class="box-content">
                    <ul>
                    @foreach (var item in Model)
                    {
                        <li>@item.Name - @item.Users.Count</li>
                    }
                    @Html.ActionLink("Yeni Role Ekle", "RoleEkle")
                    </ul>

                </div>
            </div><!--/span-->
        </div><!--/row-->
    </div>
</div>


<

HerkeseIs/HerkeseIs/Areas/Admin/Views/Role/RoleEkle.cshtml
@model HerkeseIs.Areas.Admin.Models.RoleEkleModelcs
@{
    ViewBag.Title = "RoleEkle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>RoleEkle</h2>



<div id="content" class="span10">

    <div class="container-fluid-full">
        <div class="row-fluid sortable">
            <div class="box span12">
                <div class="box-header" data-original-title>
                    
                </div>
                <div class="box-content">
                    @using (Html.BeginForm("RoleEkle", "Role", FormMethod.Post))
                    {
                        @Html.TextAreaFor(m => m.RolAd)
                        <input type="submit" />
                    }

                </div>
            </div><!--/span-->
        </div><!--/row-->
    </div>
</div>

HerkeseIs/HerkeseIs/Areas/Admin/Views/Role/RoleUserEkle.cshtml
`
@{
    ViewBag.Title = "RoleUserEkle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>RoleUserEkle</h2>